config/routes.rb
Rails.application.routes.draw do
  root 'torrents#index'
  resources :torrents
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
end

app/models/status.rb
class Status < ApplicationRecord
  validates :name, presence: true
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
  validates :name, presence: true
end

app/models/torrent.rb
class Torrent < ApplicationRecord
  belongs_to :category
  belongs_to :sub_category
  belongs_to :status

  validates :name, presence: true
  validates :torrent_hash, presence: true
  validates :category_id, presence: true
  validates :sub_category_id, presence: true
  validates :status, presence: true

  default_scope -> { order created_at: :desc }

  self.per_page = 100

  def full_category_name
    "#{category.name} - #{sub_category.name}"
  end

  def download_link
    "#"
  end

  def magnet_link
    "#"
  end

  def size
    "1MB"
  end

  def seeders
    0
  end

  def leechers
    0
  end

  def downloads
    0
  end

  def created_at_short
    created_at.strftime '%Y-%m-%d %H:%m' 
  end

  def information
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/torrents_controller.rb
class TorrentsController < ApplicationController

  def index
    @torrents = Torrent.paginate(page: params[:page])
  end

  def show
    @torrent = Torrent.find_by(id: params[:id])
    redirect_to root_path unless @torrent
  end

  def new
  end

  def create
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def category_icon torrent
    img = "#{torrent.category_id}_#{torrent.sub_category_id}.png"
    image_tag img, alt: torrent.full_category_name
  end

end

app/helpers/torrents_helper.rb
module TorrentsHelper
end

app/views/layouts/_footer.html.erb
<footer style="text-align: center;">
  <p>
    Dark Mode:
    <a id="themeToggle" href="#">Toggle</a>
  </p>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <a href="/" class="navbar-brand">Nyaa</a>
    </div>

    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Upload', new_torrent_path %></li>
        <li><%= link_to 'About', '#' %></li>
        <li><%= link_to 'RSS', '#' %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <%= fa_icon 'user fw', text: 'Guest' %>
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li>
              <a href="#"><%= fa_icon 'sign-in fw', text: 'Login' %></a>
            </li>
            <li>
              <a href="#"><%= fa_icon 'pencil fw', text: 'Register' %></a>
            </li>
          </ul>
        </li>
      </ul>

      <%= form_tag '/', method: :get, class: 'navbar-form navbar-right form' do %>
        <div class="input-group search-container">
          <div id="navFilter-criteria" class="input-group-btn nav-filter">
            <select class="selectpicker show-tick" title="Filter" data-width="120px" name="f" >
              <option class="bs-title-option" value="">Filter</option>
              <option value="0" title="No filter" selected="">No filter</option>
              <option value="1" title="No remakes">No remakes</option>
              <option value="2" title="Trusted only">Trusted only</option>
            </select>
          </div>

          <div id="navFilter-category" class="input-group-btn nav-filter">
            <select class="selectpicker show-tick" title="Category" data-width="130px" name="c">
              <option class="bs-title-option" value="">Category</option>
              <option value="0_0" title="All categories" selected="">All categories</option>
            </select>
          </div>

          <%= text_field_tag :q, '', placeholder: 'Search...', class: 'form-control search-bar' %>
          <div class="input-group-btn search-btn">
            <button class="btn btn-primary" type="submit">
              <%= fa_icon 'fw search' %>
            </button>
          </div>
        </div>
      <% end %>
      
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nyaa</title>
    <%= csrf_meta_tags %>

    <%= favicon_link_tag 'favicon.png', type: 'image/png' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/torrents/_torrent.html.erb
<tr class="default">
  <td style="padding:0 4px;">
    <a href="#" title="<%= torrent.full_category_name %>">
      <%= category_icon torrent %>
    </a>
  </td>

  <td colspan="2">
    <%= link_to torrent.name, torrent_path(torrent), title: torrent.name %>
  </td>

  <td class="text-center" style="white-space: nowrap;">
    <a href="<%= torrent.download_link %>">
      <i class="fa fa-fw fa-download"></i>
    </a>

    <a href="<%= torrent.magnet_link %>">
      <i class="fa fa-fw fa-magnet"></i>
    </a>
  </td>
      
  <td class="text-center"><%= torrent.size %></td>
  <td class="text-center" title="<%= "#{time_ago_in_words torrent.created_at} ago" %>">
    <%= torrent.created_at_short %>
  </td>
  <td class="text-center" style="color: green;"><%= torrent.seeders %></td>
  <td class="text-center" style="color: red;"><%= torrent.leechers %></td>
  <td class="text-center"><%= torrent.downloads %></td>
</tr>

app/views/torrents/index.html.erb
<div class="alert alert-info">
  <p>This is for browsing old nyaa torrents only</p>
</div>

<div class="table-responsive">
  <table class="table table-bordered table-striped table-hover torrent-list">
    <thead>
      <tr>
        <th class="hdr-category text-center" style="width:80px;">
          <div>Category</div>
        </th>
        <th class="hdr-name text-center" style="width:auto;">
          <div>Name</div>
        </th>
        <th class="hdr-comments text-center sorting" title="Comments" style="width:50px;">
          <a href="#"></a>
          <i class="fa fa-comments-o"></i>
        </th>
        <th class="hdr-link text-center" style="width:70px;">
          <div>Link</div>
        </th>
        <th class="hdr-size text-center sorting" style="width:100px;">
          <a href="#"></a>
          <div>Size</div>
        </th>
        <th class="hdr-date text-center sorting_desc" title="In local time" style="width:140px;">
          <a href="#"></a>
          <div>Date</div>
        </th>
        <th class="hdr-seeders text-center sorting" title="Seeders" style="width:50px;">
          <a href="#"></a>
          <i class="fa fa-arrow-up"></i>
        </th>
        <th class="hdr-leechers text-center sorting" title="Leechers" style="width:50px;">
          <a href="#"></a>
          <i class="fa fa-arrow-down"></i>
        </th>
        <th class="hdr-downloads text-center sorting" title="Completed downloads" style="width:50px;">
          <a href="#"></a>
          <i class="fa fa-check"></i>
        </th>
      </tr>
    </thead>

    <tbody>
      <%= render @torrents %>
    </tbody>
  </table>
</div>

<div class="text-center">
  <%= will_paginate @torrents, previous_label: '«', next_label: '»' %>
</div>

app/views/torrents/new.html.erb
<% categories =
  [{ name: 'Anime',
     sub_categories: ['Anime Music Video',
                      'English-translated',
                      'Non-English-translated',
                      'Raw',] },
   { name: 'Audio',
     sub_categories: ['Lossless',
                      'Lossy',] },
   { name: 'Literature',
     sub_categories: ['English-translated',
                      'Non-English-translated',
                      'Raw',] },
   { name: 'Live Action',
     sub_categories: ['English-translated',
                      'Idol/Promotional Video',
                      'Non-English-translated',
                      'Raw',] },
   { name: 'Pictures',
     sub_categories: ['Graphics',
                      'Photos',] },
   { name: 'Software',
     sub_categories: ['Applications',
                      'Games',] },]

  markdown_cheat_sheet_url =
    'https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet'
%>
<h1>Upload Torrent</h1>
<div id="upload-drop-zone">
  <span>Drop here!</span>
</div>

<%= form_tag torrents_path do %>
  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <%= label 'torrent',  'torrent_file' %> 
        <div class="input-group">
          <label class="input-group-btn" for="torrent_torrent_file">
            <span class="btn btn-default">Browse...</span>
          </label>
          <input class="form-control" readonly="" type="text">
        </div>
        <div class="sr-only">
          <%= file_field 'torrent', 'torrent_file', accept: '.torrent' %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= label 'torrent', 'display_name', 'Torrent display name (Optional)', class: 'control-label' %>
        <%= text_field 'torrent', 'display_name', class: 'form-control',
                                        placeholder: 'Display name',
                                        title: '', value: '' %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= label 'torrent', 'category' %>
        <select id="torrent_category" name="torrent[category]" class="form-control" title="">
          <option value="">[Select a category]</option>
          <% categories.each_with_index do |cat, i| %>
            <option disabled="" value="<%= "#{i + 1}_0" %>"><%= cat[:name] %></option>
            <% cat[:sub_categories].each_with_index do |sub_cat, j| %>
              <option value="<%= "#{i + 1}_#{j + 1}" %>"><%= "#{cat[:name]} - #{sub_cat}" %></option>
            <% end %>
          <% end %>
        </select>
      </div>
    </div>
  </div>

  <div class="row form-group">
    <div class="col-md-6">
      <div class="form-group">
        <%= label 'torrent', 'information' %>
        <%= text_field 'torrent', 'information', class: 'form-control',
                                       placeholder: 'Your website or IRC channel',
                                       title: '', value: '' %>
      </div>
    </div>
    <div class="col-md-6">
      <label class="control-label">Torrent flags</label>
      <br>
      <div class="btn-group" data-toggle="buttons">
        <label class="btn btn-default active disabled" title="Upload torrent anonymously (don't display your username)">
          <%= check_box_tag 'is_anonymous', 'y' %>
          <span class="glyphicon glyphicon-ban-circle"></span>
          Anonymous
        </label>
        <label class="btn btn-grey" title="Hide torrent from listing">
          <%= check_box_tag 'is_hidden', 'y' %>
          <span class="glyphicon glyphicon-unchecked"></span>
          <span class="glyphicon glyphicon-check"></span>
          Hidden
        </label>
      </div>
      <div class="btn-group" data-toggle="buttons">
        <label class="btn btn-danger" title="This torrent is derived from another release">
          <%= check_box_tag 'is_remake', 'y' %>
          <span class="glyphicon glyphicon-unchecked"></span>
          <span class="glyphicon glyphicon-check"></span>
          Remake
        </label>
        <label class="btn btn-warning" title="This torrent is a complete batch (eg. season)">
          <%= check_box_tag 'is_complete', 'y' %>
          <span class="glyphicon glyphicon-unchecked"></span>
          <span class="glyphicon glyphicon-check"></span>
          Complete
        </label>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <div id="description-markdown-editor" class="markdown-editor" data-field-name="description">
          <%= label 'torrent', 'description', class: 'control-label' %>
          <%= link_to 'Markdown supported', markdown_cheat_sheet_url, target: '_blank', class: 'small' %>
          <ul class="nav nav-tabs" role="tablist">
            <li class="active" role="presentation">
              <%= link_to 'Write', '#description-tab', :role => 'tab', :'data-toggle' => 'tab' %>
            </li>
            <li role="presentation">
              <%= link_to 'Preview', '#description-preview',
                :id => 'description-preview-tab', :role => 'tab', :'data-toggle' => 'tab' %>
            </li>
          </ul>
          <div class="tab-content">
            <div id="description-tab" class="tab-pane active" role="tabpanel">
              <%= text_area_tag 'torrent[description]', '', id: 'entry-markdown', class: 'form-control' %>
            </div>
            <div id="description-preview" class="tab-pane" role="tabpanel">
              <div class="well rendered-markdown"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4"></div>
  </div>
  <div class="row">
    <div class="form-group col-md-6">
      <%= submit_tag 'Upload', class: 'btn btn-primary', data: { disable_with: false } %>
    </div>
  </div>
<% end %>

app/views/torrents/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= @torrent.name %></h3>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-1">Category:</div>
      <div class="col-md-5">
        <%= link_to @torrent.category.name, "#" %>
        -
        <%= link_to @torrent.sub_category.name, '#' %>
      </div>
      <div class="col-md-1">Date:</div>
      <div class="col-md-5" title="<%= "#{time_ago_in_words @torrent.created_at} ago" %>">
        <%= @torrent.created_at_short %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-1">Submitter:</div>
      <div class="col-md-5">
        <%= link_to 'NyaaTorrents', '/' %>
      </div>
      <div class="col-md-1">Seeders:</div>
      <div class="col-md-5">
        <span style="color: green;"><%= @torrent.seeders %></span>
      </div>
    </div>
    <div class="row">
      <div class="col-md-1">Information:</div>
      <div class="col-md-5">
        <% information = @torrent.information %>
        <%= information ? link_to(information, information) : 'No information' %>
      </div>
      <div class="col-md-1">Leechers:</div>
      <div class="col-md-5">
        <span style="color: red;"><%= @torrent.leechers %></span>
      </div>
    </div>
    <div class="row">
      <div class="col-md-1">File size:</div>
      <div class="col-md-5">
        <%= @torrent.size %>
      </div>
      <div class="col-md-1">Completed:</div>
      <div class="col-md-5">
        <%= @torrent.downloads %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-offset-6 col-md-1">Info hash:</div>
      <div class="col-md-5">
        <kbd><%= @torrent.torrent_hash %></kbd>
      </div>
    </div>
  </div>
  <div class="panel-footer">
    <a href="<%= @torrent.download_link %>">
      <%= fa_icon 'fw download', text: 'Download torrent' %>
    </a>
    or
    <a href="<%= @torrent.magnet_link %>">
      <%= fa_icon 'fw magnet', text: 'Magnet' %>
    </a>
  </div>
</div>